# File: templates/build-and-test.yml

# defaults for any parameters that aren't specified
parameters: 
- name: 'pool'
  type: object
  default: {}
- name: srcProject
  default: '**/*.csproj'
- name: testProject
  default: ''
- name: dotnetVersion
  default: '6.x'
- name: buildConfiguration
  default: 'Debug'

jobs:
- job: Build
  pool: ${{ parameters.pool }}
  steps: 
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.dotnetVersion }}
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      configuration: ${{ parameters.buildConfiguration }}
      projects: ${{ parameters.srcProject }}  
  - task: DotNetCoreCLI@2
    displayName: 'Create migration'
    inputs:
      command: custom
      custom: ef
      arguments: 'migrations script -i -p InsecureWebApp -o $(Build.ArtifactStagingDirectory)/Migrations/migration.sql'
  - task: SqlAzureDacpacDeployment@1
    inputs:
      azureSubscription: $(AzureSubscription)
      AuthenticationType: 'connectionString'
      ConnectionString: 'Data Source=tcp:$(AzureDBServer),1433;Initial Catalog=$(AzureDBName);User Id=$(AzureDBUser);Password=$(AzureDBPassword)'
      deployType: 'SqlTask'
      SqlFile: '$(Build.ArtifactStagingDirectory)/Migrations/migration.sql'
      IpDetectionMethod: 'AutoDetect'  
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: $(AzureSubscription)
      appType: 'webApp'
      WebAppName: 'iwanet'
      packageForLinux: '$(Pipeline.Workspace)/InsecureWebApp.zip'
      #JSONFiles: 'appsettings.json'