# File: templates/fod-sast-scan.yml

# defaults for any parameters that aren't specified
parameters: 
- name: 'pool'
  type: object
  default: {}
- name: workingDirectory
  default: ''
- name: projectFile
- name: dotnetVersion
  default: '6.x'
- name: buildConfiguration
  default: 'Debug'
- name: vsVersion
  default: '2022'
- name: vsEdition
  default: 'Community'
- name: jdkVersion
  default: '17'
- name: jdkArch
  default: 'x64'
- name: fodApiUrl
  default: 'https://api.emea.fortify.com'
- name: fodClientId
- name: fodClientSecret
- name: fodConnection
  default: 'FODAzureDevOps'
- name: fodAppName
- name: fodReleaseName
- name: fodParentReleaseName
  default: 'main'

jobs:
- job: FoDStaticScan
  pool: ${{ parameters.pool }}
  steps:
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.dotnetVersion }}
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: ${{ parameters.jdkVersion }}
      jdkArchitectureOption: ${{ parameters.jdkArch }}
      jdkSourceOption: PreInstalled
  - task: FcliInstaller@0
    inputs:
      version: 'latest'
  - task: PowerShell@2
    displayName: 'FoD Check Release'
    inputs:
      targetType: 'inline'
      script: |
        $App="${env:FOD_APP_NAME}"
        $Rel="${env:FOD_RELEASE_NAME}"
        if (${env:FORTIFY_APP_NAME_OVERRIDE}) {
          Write-Host "##[debug]Overriding FORTIFY_APP_NAME to ${env:FORTIFY_APP_NAME_OVERRIDE}"
          Write-Host "##vso[task.setvariable variable=FORTIFY_APP_NAME]${env:FORTIFY_APP_NAME_OVERRIDE}"
          $App="${env:FORTIFY_APP_NAME_OVERRIDE}"
        } else {
          Write-Host "##[command]Using FORTIFY_APP_NAME ${App}"
          Write-Host "##vso[task.setvariable variable=FORTIFY_APP_NAME]${App}"
        }
        if (${env:FORTIFY_RELEASE_NAME_OVERRIDE}) {
          Write-Host "##[debug]Overriding FORTIFY_RELEASE_NAME to ${env:FORTIFY_RELEASE_NAME_OVERRIDE}"
          Write-Host "##vso[task.setvariable variable=FORTIFY_RELEASE_NAME]${env:FORTIFY_RELEASE_NAME_OVERRIDE}"
          $Rel=${env:FORTIFY_RELEASE_NAME_OVERRIDE}
        } else {
          Write-Host "##[debug]Using FORTIFY_RELEASE_NAME ${Rel}"
          Write-Host "##vso[task.setvariable variable=FORTIFY_RELEASE_NAME]${Rel}"
        }
        Write-Host "##[command]fcli fod session login --url ""${env:FOD_API_URL}"" --client-id ""${env:FOD_CLIENT_ID}"" --client-secret ""${env:FOD_CLIENT_SECRET}"" --session azure-pipelines"
        fcli fod session login --url ""${env:FOD_API_URL}"" --client-id ""${env:FOD_CLIENT_ID}"" --client-secret ""${env:FOD_CLIENT_SECRET}"" --session azure-pipelines
        Write-Host "##[command]fcli fod release list --app "${App}" --session azure-pipelines"
        fcli fod release list --app "${App}" --session azure-pipelines
        Write-Host "##[command]fcli fod release create ""${App}:${Rel}"" --description ""Created automatically from Azure DevOps"" --copy-from ""${App}:${env:FOD_PARENT_RELEASE_NAME}"" --status Development --skip-if-exists -o expr=""{releaseId}"" --session azure-pipelines"
        $RelId=(fcli fod release create "${App}:${Rel}" --description "Created automatically from Azure DevOps" --copy-from "${App}:${env:FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session azure-pipelines)
        Write-Host "##[debug]Setting fodReleaseId to $RelId"
        Write-Host "##vso[task.setvariable variable=fodReleaseId]$RelId"
        fcli tool sc-client install -y -d $(Build.SourcesDirectory)\sc-client
        Write-Host "##vso[task.prependpath]$(Build.SourcesDirectory)\sc-client\bin"
      showWarnings: true
    env:
      FOD_API_URL: ${{ parameters.fodApiUrl }}
      FOD_CLIENT_ID: ${{ parameters.fodClientId }}
      FOD_CLIENT_SECRET: ${{ parameters.fodClientSecret }}
      FOD_APP_NAME: ${{ parameters.fodAppName }}
      FOD_RELEASE_NAME: ${{ parameters.fodReleaseName }}
      FOD_PARENT_RELEASE_NAME: ${{ parameters.fodParentReleaseName }}
  - task: BatchScript@1
    displayName: 'Set Visual Studio environment'
    inputs:
      filename: ${{ format('C:\Program Files\Microsoft Visual Studio\{0}\{1}\Common7\Tools\VsDevCmd.bat', parameters.vsVersion, parameters.vsEdition) }}
      modifyEnvironment: true
  - task: PowerShell@2
    displayName: 'FoD SAST Scan'
    inputs:
      targetType: 'inline'
      script: |
        scancentral package -bt msbuild -f ${env:PROJ_FILE} -o ${env:PACKAGE_FILE}
        fcli fod sast-scan start --release "${env:FOD_RELEASE_ID}" --notes "${env:FOD_SCAN_NOTES}" -f ${env:PACKAGE_FILE} --store curScan --session azure-pipelines
        $ScanId=(fcli util var get ::curScan::)
        Write-Host "##vso[task.setvariable variable=fodScanId]$ScanId"
        fcli fod sast-scan wait-for ::curScan:: --session azure-pipelines
      workingDirectory: ${{ parameters.workingDirectory }}
    env:
      PROJ_FILE: ${{ parameters.projectFile }}
      FOD_RELEASE_ID: $(fodReleaseId)
      PACKAGE_FILE: "package.zip"
      FOD_SCAN_NOTES: "Triggered by Azure DevOps Pipelines"
  #
  # Change the invocation of FortifyOnDemandStatic to your required configuration.
  # Default is to use an existing release as we are checking it exists above, creating if not and using its release id.
  #
  #- task: FortifyOnDemandStatic@8
  #  displayName: 'FoD Static Scan'
  #  inputs:
  #    FortifyProjects: ${{ parameters.workingDirectory }}
  #    FodConnection: ${{ parameters.fodConnection }}
  #    ReleaseOptions: '0'
  #    ReleaseId: $(fodReleaseId)
  #    EntitlementSelection: '1'
  #    EntitlementPreference: '1'
  #    OverrideScanSettings: '2'
  #    InProgressScanActionType: '2'
  #    RemediationScanPreference: '2'
  #    BuildType: 'msbuild'
  #    BuildFile: ${{ parameters.projectFile }}
  #    PolicyFailAction: '0'
  #    PollingInterval: 5
  - task: PowerShell@2
    displayName: 'FoD Logout'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "##[command]fcli fod session logout --session azure-pipelines"
        fcli fod session logout --session azure-pipelines
