# File: templates/fod-sast-scan.yml

# defaults for any parameters that aren't specified
parameters: 
- name: vmImage
  default: 'windows-2022'
- name: pool
  default: ''
- name: srcDir
- name: buildFile
- name: dotnetVersion
  default: '6.x'
- name: buildConfiguration
  default: 'Debug'
- name: vsVersion
  default: '2022'
- name: vsEdition
  default: 'Community'
- name: jdkVersion
  default: '17'
- name: jdkArch
  default: 'x64'
- name: fodConnection
  default: 'FODAzureDevOps'
- name: fodReleaseId

jobs:
- job: FoDStaticScan
  pool: 
    name: ${{ parameters.pool }}
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: UseDotNet@2
    inputs:
      version: ${{ parameters.dotnetVersion }}
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: ${{ parameters.jdkVersion }}
      jdkArchitectureOption: ${{ parameters.jdkArch }}
      jdkSourceOption: PreInstalled
  - task: FcliInstaller@0
    inputs:
      version: 'latest'
  - task: BatchScript@1
    displayName: 'Set Visual Studio environment'
    inputs:
      filename: ${{ format('C:\Program Files\Microsoft Visual Studio\{0}\{1}\Common7\Tools\VsDevCmd.bat', parameters.vsVersion, parameters.vsEdition) }}
      modifyEnvironment: true
  - task: FortifyOnDemandStatic@8
    inputs:
      FortifyProjects: ${{ parameters.srcDir }}
      FodConnection: ${{ parameters.fodConnection }}
      ReleaseOptions: '0'
      ReleaseId: ${{ parameters.fodReleaseId }}
      EntitlementSelection: '1'
      EntitlementPreference: '1'
      OverrideScanSettings: '2'
      InProgressScanActionType: '2'
      RemediationScanPreference: '2'
      BuildType: 'msbuild'
      BuildFile: ${{ parameters.buildFile }}
      PolicyFailAction: '0'
      PollingInterval: 5