# File: templates/simulate-deployment.yml

# defaults for any parameters that aren't specified
parameters: 
- name: vmImage
  default: 'windows-2022'
- name: pool
  default: ''
- name: demands
  default: ''
- name: workingDirectory
  default: $(Build.SourcesDirectory).

jobs:
- job: Build
  pool: 
    name: ${{ parameters.pool }}
    #demands: ${{ parameters.demands }}
    vmImage: ${{ parameters.vmImage }}
  steps: 
  - task: CmdLine@2
    inputs:
      script: |
        echo "Deploying application..."
        dir
      workingDirectory:  ${{ parameters.workingDirectory }}