# Example Continuous Delivery Pipeline with Fortify on Demand (FoD) and Fortify ScanCentral support
name: InsecureWebApp-CD

trigger:
  batch: true
  branches:
    include:
    - main
    - develop
    - features/*
    - releases/*
    exclude:
    - experimental/*
  paths:
    exclude:
    - InsecureProductService/
    - InsecurePaymentService/
    - InsecureShippingService/
    - README.md
    - bin/*
    - lib/*
    - etc/*
    - media/*

pr:
  branches:
    include:
    - main
    - develop
  paths:
    exclude:
    - InsecureProductService/
    - InsecurePaymentService/
    - InsecureShippingService/
    - README.md
    - bin/*
    - lib/*
    - etc/*
    - media/*
  
variables:

  #
  # In order for the pipeline to execute successfully you should create the following variables in the Pipeline UI.
  # 
  # For FoD:
  #   FOD_API_URL                   - FoD API URL, e.g. "https://api.ams.fortify.com"
  #   FOD_CLIENT_ID                 - FoD API Client Id
  #   FOD_CLIENT_SECRET             - FoD API Client Secret
  #
  # For SSC:
  #   SSC_URL                       - SSC URL
  #   SSC_CI_TOKEN                  - SSC CIToken
  #
  # For ScanCentral SAST:
  #   SCANCENTRAL_CTRL_URL          - ScanCentral SAST Controller URL
  #   SCANCENTRAL_CLIENT_AUTH_TOKEN - ScanCentral SAST Client Authentication Token
  #
  # For ScanCentral DAST:
  
  # Change these variables depending on which parts of the pipeline to execute:
- name: USE_FOD_SAST
  value: true
- name: USE_FOD_OSS
  value: false
- name: USE_FOD_DAST
  value: false
- name: USE_SCANCENTRAL_SAST
  value: false
- name: USE_SCANCENTRAL_DAST
  value: false

  #
  # By default the FoD/SSC application name is set to the name of the Git repository
  # By default the FoD/SSC release/application version name is set to the name of the Git branch
  # If you wish to override any of these please set the following variables from the pipelines UI:
  #
  # FORTIFY_APP_NAME_OVERRIDE
  # FORTIFY_RELEASE_NAME_OVERRIDE
  #
- name: FORTIFY_APP_NAME
  value: $(Build.Repository.Name)
- name: FORTIFY_RELEASE_NAME
  value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

  # IMPORTANT: if using a self-hosted agent, please ensure a Java 17x64 SDK is installed and the environment variable JAVA_HOME_17_X64 is set to its location

stages:

  #
  # Build and Unit Test the application components
  #
- stage: BuildAndUnitTest
  displayName: 'Build and Unit Test'
  jobs:
    # Build InsecureWebApp and run its tests
  - template: 'devops-integrations/azure-pipelines/templates/build-and-test.yml'
    parameters:
        srcProject: 'InsecureWebApp/InsecureWebApp.csproj' 
        testProject: 'InsecureWebAppTests/InsecureWebAppTests.csproj'
        pool:
            name: 'Fortify' # use named self-hosted pool 
            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool

  #
  # Static Application Security Testing with Fortify on Demand
  #
- stage: FoD_SAST
  displayName: 'FoD SAST'
  condition: eq(variables['USE_FOD_SAST'], 'true') 
  dependsOn: 
    - BuildAndUnitTest
  jobs:
    # Run FoD SAST Scan on Project
  - template: 'devops-integrations/azure-pipelines/templates/fod-sast-scan.yml'
    parameters:
        workingDirectory: 'InsecureWebApp' 
        projectFile: 'InsecureWebApp.csproj'
        fodApiUrl: $(FOD_API_URL)
        fodClientId: $(FOD_CLIENT_ID)
        fodClientSecret: $(FOD_CLIENT_SECRET)
        #fodConnection: "FoDAzureDevops" # this is defaulted but can be overriden here if connection name is different
        fodAppName: "$(FORTIFY_APP_NAME)"
        fodReleaseName: "$(FORTIFY_RELEASE_NAME)"
        pool:
            name: 'Fortify' # use named self-hosted pool 
            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool

  #
  # Static Application Security Testing with ScanCentral SAST (on premise)
  #
- stage: ScanCentral_SAST
  displayName: 'ScanCentral SAST'
  condition: eq(variables['USE_SCANCENTRAL_SAST'], 'true')
  dependsOn:
    - BuildAndUnitTest
  jobs:
    # Run Scancentral SAST Scan on Project
  - template: 'devops-integrations/azure-pipelines/templates/scancentral-sast-scan.yml'
    parameters:
        workingDirectory: 'InsecureWebApp' 
        projectFile: 'InsecureWebApp.csproj'
        scanCentralCtrlUrl: $(SCANCENTRAL_CTRL_URL)
        scanCentralClientToken: $(SCANCENTRAL_CLIENT_AUTH_TOKEN)
        sscUrl: $(SSC_URL)
        sscCiToken: $(SSC_CI_TOKEN)
        sscAppName: "$(FORTIFY_APP_NAME)"
        sscAppVerName: "$(FORTIFY_RELEASE_NAME)"
        #notificationEmail: 'your_email_address'
        pool:
            name: 'Fortify' # use named self-hosted pool 
            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool

  # 
  # Deploy the application - this is an example of deploying a web application and its database to Azure
  #
- stage: DeployApp
  displayName: 'Deploy Application'
  dependsOn: 
    - BuildAndUnitTest
    - ScanCentral_SAST
    - FoD_SAST
  jobs: 
    # This is a simulated deployment and does nothing
  - template: 'devops-integrations/azure-pipelines/templates/simulate-deployment.yml'
    parameters:
        workingDirectory: 'InsecureWebApp'
        pool:
            name: 'Fortify' # use named self-hosted pool 
            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool
    # More likely you will use something like the following to deploy the application to Azure
#  - template: 'devops-integrations/azure-pipelines/templates/deploy-to-azure.yml'
#    parameters:
#        srcProject: 'InsecureWebApp/InsecureWebApp.csproj' 
#        pool:
#            name: 'Fortify' # use named self-hosted pool 
#            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool

#
# Dynamic Application Security Testing with ScanCentral DAST (on-premise)
#        
- stage: ScanCentral_DAST
  displayName: 'ScanCentral DAST'
  condition: eq(variables['USE_SCANCENTRAL_DAST'], 'true')
  dependsOn: DeployApp
  jobs:
    # Run ScanCentral DAST Scan on Project
  - template: 'devops-integrations/azure-pipelines/templates/fod-dast-scan.yml'
    parameters:
        fodApiKey: '${FoDClientId}' 
        fodApiSecret: '${FoDClientSecret}'
        fodReleaseId: $(FoDReleaseId)
        skip: true
        pool:
            name: 'Fortify' # use named self-hosted pool 
            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool

  #
  # Dynamic Application Security Testing with Fortify on Demand
  #
- stage: FoD_DAST
  displayName: 'FoD DAST'
  condition: eq(variables['USE_FOD_DAST'], 'true') 
  dependsOn: DeployApp
  jobs:
    # Run FoD DAST Scan on Project
  - template: 'devops-integrations/azure-pipelines/templates/fod-dast-scan.yml'
    parameters:
        fodApiKey: '${FoDClientId}' 
        fodApiSecret: '${FoDClientSecret}'
        fodReleaseId: $(FoDReleaseId)
        skip: true
        pool:
            name: 'Fortify' # use named self-hosted pool 
            #vmImage: 'windows-2022' # or uncomment to use Azure Devops cloud-hosted pool