# File: templates/build-and-test.yml

# defaults for any parameters that aren't specified
parameters: 
- name: vmImage
  default: 'windows-2022'
- name: pool
  default: ''
- name: srcProject
  default: '**/*.csproj'
- name: testProject
  default: ''
- name: dotnetVersion
  default: '6.x'
- name: buildConfiguration
  default: 'Debug'
- name: runTests
  type: boolean
  default: true

jobs:
- job: Build
  pool: 
    name: ${{ parameters.pool }}
    vmImage: ${{ parameters.vmImage }}
    steps:
    - bash: |
        if [ -z "SRCPROJECT" ]; then
          echo "##vso[task.logissue type=error;]Missing template parameter \"srcProject\""
          echo "##vso[task.complete result=Failed;]"
        fi
      env:
        SRCPROJECT: ${{ parameters.srcProject }}
      displayName: Check for required parameters
    - task: UseDotNet@2
      inputs:
        version: ${{ parameters.dotnetVersion }}
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        configuration: ${{ parameters.buildConfiguration }}
        projects: ${{ parameters.srcProject }}
- job: UnitTest
  dependsOn: Build
  condition: eq('${{ parameters.runTests }}', true)
  pool: 
    name: ${{ parameters.pool }}
    vmImage: ${{ parameters.vmImage }}
    steps:
    - task: UseDotNet@2
      inputs:
        version: ${{ parameters.dotnetVersion }}
    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: 'test'
        configuration: ${{ parameters.buildConfiguration }}
        projects: ${{ parameters.testProject }}