# Example Continuous Delivery Pipeline with Fortify on Premise (SCA/SSC) and/or Fortify on Demand (FOD) support

trigger:
  batch: true
  branches:
    include:
    - main
    - develop
    - features/*
    - releases/*
    exclude:
    - experimental/*
  paths:
    include:
    - InsecurePaymentService/

pr:
  branches:
    include:
    - main
  paths:
    include:
    - InsecurePaymentService/
  
variables:

  templatesDir: 'devops-integrations/azure/templates'

stages:

  #
  # Build and Unit Test the application components
  #
- stage: BuildAndUnitTest
  displayName: 'Build and Unit Test'
  jobs:
    # Build InsecurePaymentService and run its tests
  - template: '../devops-integrations/azure/templates/build-and-test.yml'
    parameters:
        srcProject: 'InsecurePaymentService/InsecurePaymentService.csproj' 
        pool: 'Fortify'
        runTests: false